name: (Test for Apple Silicon) Build and upload python package to PyPI

on:
  workflow_dispatch

jobs:
  release-pypi:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Build package and upload (macOS)
      if: runner.os == 'macOS'
      run: bash release-test-pypi-macos-arm.sh
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
